[0.000000] (-) TimerEvent: {}
[0.000665] (motor) JobQueued: {'identifier': 'motor', 'dependencies': OrderedDict()}
[0.001306] (testt) JobQueued: {'identifier': 'testt', 'dependencies': OrderedDict()}
[0.002408] (motor) JobStarted: {'identifier': 'motor'}
[0.095565] (testt) JobStarted: {'identifier': 'testt'}
[0.102270] (-) TimerEvent: {}
[0.205383] (-) TimerEvent: {}
[0.306323] (-) TimerEvent: {}
[0.407094] (-) TimerEvent: {}
[0.507814] (-) TimerEvent: {}
[0.608464] (-) TimerEvent: {}
[0.709061] (-) TimerEvent: {}
[0.809663] (-) TimerEvent: {}
[0.910290] (-) TimerEvent: {}
[1.011007] (-) TimerEvent: {}
[1.111792] (-) TimerEvent: {}
[1.213010] (-) TimerEvent: {}
[1.313967] (-) TimerEvent: {}
[1.414675] (-) TimerEvent: {}
[1.515369] (-) TimerEvent: {}
[1.615978] (-) TimerEvent: {}
[1.716575] (-) TimerEvent: {}
[1.817259] (-) TimerEvent: {}
[1.917912] (-) TimerEvent: {}
[2.018610] (-) TimerEvent: {}
[2.119863] (-) TimerEvent: {}
[2.221491] (-) TimerEvent: {}
[2.322361] (-) TimerEvent: {}
[2.423199] (-) TimerEvent: {}
[2.523907] (-) TimerEvent: {}
[2.624644] (-) TimerEvent: {}
[2.725381] (-) TimerEvent: {}
[2.826026] (-) TimerEvent: {}
[2.926721] (-) TimerEvent: {}
[3.027517] (-) TimerEvent: {}
[3.129249] (-) TimerEvent: {}
[3.230629] (-) TimerEvent: {}
[3.331346] (-) TimerEvent: {}
[3.432495] (-) TimerEvent: {}
[3.517498] (testt) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 67, in execute\n    loop.run_until_complete(future)\n  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete\n    self.run_forever()\n  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever\n    self._run_once()\n  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once\n    event_list = self._selector.select(timeout)\n  File "/usr/lib/python3.8/selectors.py", line 468, in select\n    fd_event_list = self._selector.poll(timeout, max_ev)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 105, in build\n    return await extension.build(additional_hooks=additional_hooks)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 59, in build\n    available_commands = await self._get_available_commands(\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 142, in _get_available_commands\n    output = await check_output(\n  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 128, in check_output\n    assert not rc, f\'Expected {args} to pass: {stderr_data}\'\nAssertionError: Expected [\'/usr/bin/python3\', \'setup.py\', \'--help-commands\'] to pass: Traceback (most recent call last):\n  File "setup.py", line 5, in <module>\n    setup(\n  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup\n    return distutils.core.setup(**attrs)\n  File "/usr/lib/python3.8/distutils/core.py", line 134, in setup\n    ok = dist.parse_command_line()\n  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 707, in parse_command_line\n    result = _Distribution.parse_command_line(self)\n  File "/usr/lib/python3.8/distutils/dist.py", line 480, in parse_command_line\n    if self.handle_display_options(option_order):\n  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1092, in handle_display_options\n    return _Distribution.handle_display_options(self, option_order)\n  File "/usr/lib/python3.8/distutils/dist.py", line 683, in handle_display_options\n    self.print_commands()\n  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 843, in print_commands\n    cmdclass = ep.resolve()\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve\n    module = __import__(self.module_name, fromlist=[\'__name__\'], level=0)\n  File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 15, in <module>\n    from setuptools.lib2to3_ex import Mixin2to3\n  File "/usr/lib/python3/dist-packages/setuptools/lib2to3_ex.py", line 12, in <module>\n    from lib2to3.refactor import RefactoringTool, get_fixers_from_package\n  File "/usr/lib/python3.8/lib2to3/refactor.py", line 26, in <module>\n    from .fixer_util import find_root\n  File "/usr/lib/python3.8/lib2to3/fixer_util.py", line 7, in <module>\n    from .pygram import python_symbols as syms\n  File "/usr/lib/python3.8/lib2to3/pygram.py", line 32, in <module>\n    python_grammar = driver.load_packaged_grammar("lib2to3", _GRAMMAR_FILE)\n  File "/usr/lib/python3.8/lib2to3/pgen2/driver.py", line 158, in load_packaged_grammar\n    return load_grammar(grammar_source)\n  File "/usr/lib/python3.8/lib2to3/pgen2/driver.py", line 121, in load_grammar\n    g = pgen.generate_grammar(gt)\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 385, in generate_grammar\n    p = ParserGenerator(filename)\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 21, in __init__\n    self.dfas, self.startsymbol = self.parse()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 155, in parse\n    a, z = self.parse_rhs()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 251, in parse_rhs\n    a, z = self.parse_alt()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 271, in parse_alt\n    c, d = self.parse_item()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 280, in parse_item\n    a, z = self.parse_rhs()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 251, in parse_rhs\n    a, z = self.parse_alt()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 271, in parse_alt\n    c, d = self.parse_item()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 280, in parse_item\n    a, z = self.parse_rhs()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 261, in parse_rhs\n    a, z = self.parse_alt()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 271, in parse_alt\n    c, d = self.parse_item()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 281, in parse_item\n    self.expect(token.OP, "]")\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 318, in expect\n    self.gettoken()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 322, in gettoken\n    tup = next(self.generator)\n  File "/usr/lib/python3.8/lib2to3/pgen2/tokenize.py", line 450, in generate_tokens\n    spos, epos, pos = (lnum, start), (lnum, end), end\nKeyboardInterrupt\n\n'}
[3.521107] (testt) JobEnded: {'identifier': 'testt', 'rc': 'SIGINT'}
[3.523043] (motor) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 67, in execute\n    loop.run_until_complete(future)\n  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete\n    self.run_forever()\n  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever\n    self._run_once()\n  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once\n    event_list = self._selector.select(timeout)\n  File "/usr/lib/python3.8/selectors.py", line 468, in select\n    fd_event_list = self._selector.poll(timeout, max_ev)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 105, in build\n    return await extension.build(additional_hooks=additional_hooks)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 59, in build\n    available_commands = await self._get_available_commands(\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 142, in _get_available_commands\n    output = await check_output(\n  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 128, in check_output\n    assert not rc, f\'Expected {args} to pass: {stderr_data}\'\nAssertionError: Expected [\'/usr/bin/python3\', \'setup.py\', \'--help-commands\'] to pass: Traceback (most recent call last):\n  File "setup.py", line 5, in <module>\n    setup(\n  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup\n    return distutils.core.setup(**attrs)\n  File "/usr/lib/python3.8/distutils/core.py", line 134, in setup\n    ok = dist.parse_command_line()\n  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 707, in parse_command_line\n    result = _Distribution.parse_command_line(self)\n  File "/usr/lib/python3.8/distutils/dist.py", line 480, in parse_command_line\n    if self.handle_display_options(option_order):\n  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1092, in handle_display_options\n    return _Distribution.handle_display_options(self, option_order)\n  File "/usr/lib/python3.8/distutils/dist.py", line 683, in handle_display_options\n    self.print_commands()\n  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 843, in print_commands\n    cmdclass = ep.resolve()\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve\n    module = __import__(self.module_name, fromlist=[\'__name__\'], level=0)\n  File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 15, in <module>\n    from setuptools.lib2to3_ex import Mixin2to3\n  File "/usr/lib/python3/dist-packages/setuptools/lib2to3_ex.py", line 12, in <module>\n    from lib2to3.refactor import RefactoringTool, get_fixers_from_package\n  File "/usr/lib/python3.8/lib2to3/refactor.py", line 26, in <module>\n    from .fixer_util import find_root\n  File "/usr/lib/python3.8/lib2to3/fixer_util.py", line 7, in <module>\n    from .pygram import python_symbols as syms\n  File "/usr/lib/python3.8/lib2to3/pygram.py", line 32, in <module>\n    python_grammar = driver.load_packaged_grammar("lib2to3", _GRAMMAR_FILE)\n  File "/usr/lib/python3.8/lib2to3/pgen2/driver.py", line 158, in load_packaged_grammar\n    return load_grammar(grammar_source)\n  File "/usr/lib/python3.8/lib2to3/pgen2/driver.py", line 121, in load_grammar\n    g = pgen.generate_grammar(gt)\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 385, in generate_grammar\n    p = ParserGenerator(filename)\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 21, in __init__\n    self.dfas, self.startsymbol = self.parse()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 155, in parse\n    a, z = self.parse_rhs()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 251, in parse_rhs\n    a, z = self.parse_alt()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 271, in parse_alt\n    c, d = self.parse_item()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 280, in parse_item\n    a, z = self.parse_rhs()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 251, in parse_rhs\n    a, z = self.parse_alt()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 271, in parse_alt\n    c, d = self.parse_item()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 280, in parse_item\n    a, z = self.parse_rhs()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 261, in parse_rhs\n    a, z = self.parse_alt()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 271, in parse_alt\n    c, d = self.parse_item()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 281, in parse_item\n    self.expect(token.OP, "]")\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 318, in expect\n    self.gettoken()\n  File "/usr/lib/python3.8/lib2to3/pgen2/pgen.py", line 322, in gettoken\n    tup = next(self.generator)\n  File "/usr/lib/python3.8/lib2to3/pgen2/tokenize.py", line 450, in generate_tokens\n    spos, epos, pos = (lnum, start), (lnum, end), end\nKeyboardInterrupt\n\n'}
[3.525213] (motor) JobEnded: {'identifier': 'motor', 'rc': 'SIGINT'}
[3.531209] (-) EventReactorShutdown: {}
